# server config
server:
  ip: 127.0.0.1
  port: 8081
# mysql config
mysql:
  user: root
  password: WJGUchenwei2000
  address: 124.70.201.39
  port: 3306
  dbname: graduate_design
  config: charset=utf8&parseTime=True&loc=Local
# redis config
redis:
  address: 124.70.201.39:6379
  password: 200010
# mongodb config
mongo:
  address: 124.70.201.39:27017
  user: superAdmin
  password: WJGUchenwei2000
  dbname:
# log config
log:
  filepath: log/log.log
mail:
  address: lutasam@sina.com
  username: lutasam@sina.com
  host: smtp.sina.com
  port: 25
  auth: 465badbff16e0582
file:
  imgs:
    # address: /share/public/imgs/
    address: imgs/
    # linux: /share/public/imgs/
    # Windows: imgs/
    # url: http://124.70.201.39:8080/imgs/
    url: http://localhost:8081/imgs/
    # linux: http://124.70.201.39:8080/imgs/
    # Windows: http://localhost:8081/imgs/
  files:
    address: /share/public/files/
    # linux: /share/public/files/
    # Windows: files/
sock:
  host: 127.0.0.1
  port: 8000